-name: Elastic search cluster
 hosts: nodes
 roles: 
  -role: elastic.elasticsearch
 vars:  
    es_config:
	node.name: “{{  node_name }}”
	cluster.name: “{{ cluster_name }}”
	network.host= 0.0.0.0
	discovery.seed_hosts: “{{  seed_hosts }}”
	clister.initial_master_nodes: “{{ initial_master_nodes }}”
